"""add hotels and route stops

Revision ID: 81c18eeee743
Revises: f6a9d0e1b2c4
Create Date: 2026-08-10 20:47:10.670613
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "81c18eeee743"
down_revision: str | None = "f6a9d0e1b2c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("star_rating", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hotels_city"), "hotels", ["city"], unique=False)
    op.create_index(op.f("ix_hotels_name"), "hotels", ["name"], unique=False)
    op.create_table(
        "route_stops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tour_id", sa.UUID(), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_route_stops_tour_id"), "route_stops", ["tour_id"], unique=False)
    op.create_table(
        "tour_hotels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tour_id", sa.UUID(), nullable=False),
        sa.Column("hotel_id", sa.UUID(), nullable=False),
        sa.Column("night_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tour_hotels_hotel_id"), "tour_hotels", ["hotel_id"], unique=False)
    op.create_index(op.f("ix_tour_hotels_tour_id"), "tour_hotels", ["tour_id"], unique=False)
    op.create_table(
        "route_stop_boarding_points",
        sa.Column("route_stop_id", sa.UUID(), nullable=False),
        sa.Column("boarding_point_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["boarding_point_id"], ["boarding_points.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_stop_id"], ["route_stops.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("route_stop_id", "boarding_point_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_stop_boarding_points")
    op.drop_index(op.f("ix_tour_hotels_tour_id"), table_name="tour_hotels")
    op.drop_index(op.f("ix_tour_hotels_hotel_id"), table_name="tour_hotels")
    op.drop_table("tour_hotels")
    op.drop_index(op.f("ix_route_stops_tour_id"), table_name="route_stops")
    op.drop_table("route_stops")
    op.drop_index(op.f("ix_hotels_name"), table_name="hotels")
    op.drop_index(op.f("ix_hotels_city"), table_name="hotels")
    op.drop_table("hotels")
    # ### end Alembic commands ###
