"""add_tour_categories_and_gallery

Revision ID: 8672234703d6
Revises: c6d9522bd833
Create Date: 2026-08-10 05:19:47.993897
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8672234703d6"
down_revision: str | None = "c6d9522bd833"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tour_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tour_categories_name"), "tour_categories", ["name"], unique=False)
    op.create_index(op.f("ix_tour_categories_slug"), "tour_categories", ["slug"], unique=True)
    op.create_table(
        "tour_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tour_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tour_images_tour_id"), "tour_images", ["tour_id"], unique=False)
    op.add_column("tours", sa.Column("image_url", sa.String(length=500), nullable=True))
    op.add_column("tours", sa.Column("category_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_tours_category_id"), "tours", ["category_id"], unique=False)
    op.create_foreign_key(
        "fk_tours_category_id_tour_categories",
        "tours",
        "tour_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )

    for table_name in ("tour_categories", "tour_images"):
        op.execute(
            f"CREATE TRIGGER {table_name}_set_updated_at "
            f"BEFORE UPDATE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in ("tour_images", "tour_categories"):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_set_updated_at ON {table_name}")
    op.drop_constraint("fk_tours_category_id_tour_categories", "tours", type_="foreignkey")
    op.drop_index(op.f("ix_tours_category_id"), table_name="tours")
    op.drop_column("tours", "category_id")
    op.drop_column("tours", "image_url")
    op.drop_index(op.f("ix_tour_images_tour_id"), table_name="tour_images")
    op.drop_table("tour_images")
    op.drop_index(op.f("ix_tour_categories_slug"), table_name="tour_categories")
    op.drop_index(op.f("ix_tour_categories_name"), table_name="tour_categories")
    op.drop_table("tour_categories")
    # ### end Alembic commands ###
