"""add_tour_agency_models

Revision ID: 93a737e4e86e
Revises: 20260808_0001
Create Date: 2026-08-09 21:20:12.373365
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "93a737e4e86e"
down_revision: str | None = "20260808_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boarding_points",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boarding_points_name"), "boarding_points", ["name"], unique=False)
    op.create_table(
        "tours",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("nights", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tours_slug"), "tours", ["slug"], unique=True)
    op.create_table(
        "tour_boarding_points",
        sa.Column("tour_id", sa.UUID(), nullable=False),
        sa.Column("boarding_point_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["boarding_point_id"], ["boarding_points.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tour_id", "boarding_point_id"),
    )
    op.create_table(
        "tour_departures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tour_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_quota", sa.Integer(), nullable=False),
        sa.Column("available_seats", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tour_id"], ["tours.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tour_departures_start_date"), "tour_departures", ["start_date"], unique=False
    )
    op.drop_constraint(op.f("contents_slug_key"), "contents", type_="unique")
    op.drop_index(op.f("ix_contents_slug"), table_name="contents")
    op.create_index(op.f("ix_contents_slug"), "contents", ["slug"], unique=True)
    op.drop_constraint(op.f("settings_key_key"), "settings", type_="unique")
    op.drop_index(op.f("ix_settings_key"), table_name="settings")
    op.create_index(op.f("ix_settings_key"), "settings", ["key"], unique=True)
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    for table_name in ("boarding_points", "tours", "tour_departures"):
        op.execute(
            f"CREATE TRIGGER {table_name}_set_updated_at "
            f"BEFORE UPDATE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in ("tour_departures", "tours", "boarding_points"):
        op.execute(f"DROP TRIGGER IF EXISTS {table_name}_set_updated_at ON {table_name}")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_settings_key"), table_name="settings")
    op.create_index(op.f("ix_settings_key"), "settings", ["key"], unique=False)
    op.create_unique_constraint(
        op.f("settings_key_key"), "settings", ["key"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_contents_slug"), table_name="contents")
    op.create_index(op.f("ix_contents_slug"), "contents", ["slug"], unique=False)
    op.create_unique_constraint(
        op.f("contents_slug_key"), "contents", ["slug"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_tour_departures_start_date"), table_name="tour_departures")
    op.drop_table("tour_departures")
    op.drop_table("tour_boarding_points")
    op.drop_index(op.f("ix_tours_slug"), table_name="tours")
    op.drop_table("tours")
    op.drop_index(op.f("ix_boarding_points_name"), table_name="boarding_points")
    op.drop_table("boarding_points")
    # ### end Alembic commands ###
