"""add_booking_model

Revision ID: c6d9522bd833
Revises: 93a737e4e86e
Create Date: 2026-08-09 21:25:35.202186
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c6d9522bd833"
down_revision: str | None = "93a737e4e86e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("departure_id", sa.UUID(), nullable=False),
        sa.Column("boarding_point_id", sa.UUID(), nullable=True),
        sa.Column("seat_count", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "CANCELLED", name="bookingstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["boarding_point_id"], ["boarding_points.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["departure_id"], ["tour_departures.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookings_departure_id"), "bookings", ["departure_id"], unique=False)
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(op.f("ix_bookings_user_id"), "bookings", ["user_id"], unique=False)

    op.execute(
        "CREATE TRIGGER bookings_set_updated_at "
        "BEFORE UPDATE ON bookings "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS bookings_set_updated_at ON bookings")
    op.drop_index(op.f("ix_bookings_user_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_departure_id"), table_name="bookings")
    op.drop_table("bookings")
    sa.Enum(name="bookingstatus").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
